add dtn7zero service and demo scenario
dtn7/dtn7-showroom pull request #4
Opened 2023-05-31 15:07 UTC by lh70

Added dtn7zero as a dependency, a configurable dtn7zero service, and a demo scenario containing both dtn7zero and dtn7-rs.

2023-06-01 12:22 UTC, gh0st42 requested changes
Thank you for the PR.
some minor questions remain.

2023-06-01 12:22 UTC, gh0st42 commented on parse_weather_data.py
the file should be renamed to something like `prepare_weather_data.py` as it does more than just parsing it.
as far as i can tell, it downloads data, unpacks it and converts it.

2023-06-01 12:22 UTC, gh0st42 commented on parse_weather_data.py
> +        json.dump(temperatures, f)
why not work with CSVs directly? why use JSON for flat row data?

2023-06-01 12:22 UTC, gh0st42 commented on Dockerfile
> +RUN cd /app && git clone --recurse-submodules https://github.com/dtn7/dtn7zero.git && \
why not install the whole lib here from the specified commit hash? the previous pip3 install might get out of sync and install a wrong version

2023-06-01 15:58 UTC, lh70 commented on parse_weather_data.py
> +        json.dump(temperatures, f)
the idea was to bring the data into exactly the format we need, so there is less overhead (loading+parsing) on demo-startup, and there is less code in the demo.

2023-06-01 16:03 UTC, lh70 commented on Dockerfile
> +RUN cd /app && git clone --recurse-submodules https://github.com/dtn7/dtn7zero.git && \
The commit-hash is equivalent to the version packed & uploaded to PyPi, so there should not be any inconsistencies. The repository is cloned only to have access to the example-scripts. It is currently not used and could also just be removed from the showroom entirely.

2023-06-03 12:09 UTC, lh70 commented on Dockerfile
> +RUN cd /app && git clone --recurse-submodules https://github.com/dtn7/dtn7zero.git && \
the unnecessary repository checkout is now removed entirely

2023-06-03 12:10 UTC, lh70 commented on parse_weather_data.py
the script is now renamed to prepare_weather_data.py

2023-06-13 19:51 UTC, merged